# Generated by Django 5.1.1 on 2024-10-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="city_images/"),
        ),
    ]
