# Generated by Django 5.1.1 on 2024-10-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0002_city_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
