# Generated by Django 5.1.1 on 2024-10-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0003_city_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="../gps_simulation/media/city_images"
            ),
        ),
    ]
