# Generated by Django 5.1.1 on 2024-11-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0004_alter_city_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="city_images"),
        ),
    ]
