# Generated by Django 5.1.1 on 2024-11-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("routes", "0007_touristplace"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="poblacion",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
